/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.java.com.amco.amcoticketmt.utils;

/**
 *
 * @author user
 */
public enum PropName {
    UNIQUEZINBUS,
    localRouteId,
    MultipleTickets,
    Show25Discount,
    UsePrinter,
    Language,
    Vendor,
    Device,
    URL,
    URLZ,
    URLP,
    TickThread,
    PositionThread,
    ZetaThread,
    NextBusStopThread,
    BoostrapThread,
    uuid,
    device,
    SerialPort,
    BaudRate,
    PrintTicketByCard,
    BustecRearIp,
    BustecMiddleIp,
    BustecFrontIp,
    BustecPort,
    TFTIP,
    TFTPORT,
    DistanceThreshold,
    DistanceStartThreshold,
    FTPSERVERIP,
    FTP_USER,
    FTP_PASSWORD,
    FTP_JSON_FILE,
    FTP_MEDIA_FILE,
    FTP_DOWNLOAD_PATH,
    PISMEDIAPATH,
    AMGATESERVER,
    ThreadPoolSize,
    DatabaseUpdateServer,
    IssueTicketServer,
    ValidateTicketServer,
    ZServer,
    CardTransactionServer,
    showStopSelectPanel,
    amountDecimalDigits,
    USEINFOTRIPNEXTSTOP,
    cardReaderPort,
    autoCardReader,
    AudioFilePathTemplate,
    loginWithCard,
    HeartbeatServer,
    ValidateWindowTimeOut,
    FTP_DOWNLOAD_PATH_PIS,
    REMOTE_FTP_DOWNLOAD_PATH_PIS,
    REMOTE_FTP_DOWNLOAD_PATH_PLAYLIST,
    FTP_DOWNLOAD_PATH_SOUNDS,
    REMOTE_FTP_DOWNLOAD_PATH_SOUNDS,
    UNZIP_SOUNDS_FILE,
    TestAudioFilePath,
    NetworkIndicationsRefreshRateSec,
    CleanupThresholdInDays,
    TicketDownloadCurrentVersionService,
    TicketFindCurrentVersionService,
    RestartAfterUpgrade,
    LCDImagesPath,
    LPCMessageDuration,
    LPCManagerMainenanceJobsIntervalSecs,
    LPCQueueSize;
}

